name: Crypto Screener Automation

on:
  schedule:
    - cron: '0 * * * *' # Berjalan otomatis setiap jam
  workflow_dispatch: # Tombol manual di tab Actions

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Execute Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
