name: Crypto Screener 1H 4H

on:
  schedule:
    # Berjalan setiap jam pada menit ke-5
    # Format Cron: (Menit) (Jam) (Hari) (Bulan) (Hari dalam Minggu)
    - cron: '5 * * * *'
  workflow_dispatch: # Tombol untuk menjalankan manual di tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install ccxt pandas pandas_ta requests

      - name: Run Screener
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python scanner.py
